package com.csis3275;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class CustomerBookingBBTesting {

	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	  @Test
	  public void booking() {
	    driver.get("http://localhost:8080/");
	    driver.manage().window().setSize(new Dimension(1264, 666));
	    driver.findElement(By.cssSelector("body")).click();
	    driver.findElement(By.id("usernameForm")).click();
	    driver.findElement(By.id("usernameForm")).sendKeys("doeJohn");
	    driver.findElement(By.id("passwordForm")).click();
	    driver.findElement(By.id("passwordForm")).sendKeys("passJohnDoe");
	    driver.findElement(By.cssSelector(".btn")).click();
	    driver.findElement(By.id("startDateFormControl")).click();
	    driver.findElement(By.id("startDateFormControl")).sendKeys("01/01/2021");
	    driver.findElement(By.id("endDateFormControl")).click();
	    driver.findElement(By.id("endDateFormControl")).sendKeys("01/10/2021");
	    driver.findElement(By.id("submitSearch")).click();
		driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
	    driver.findElement(By.linkText("Book a Room")).click();
	    driver.findElement(By.cssSelector(".btn:nth-child(6)")).click();
	    driver.findElement(By.cssSelector(".confirm-booking")).click();
	    driver.findElement(By.linkText("Delete")).click();
	    driver.findElement(By.cssSelector(".btn-danger")).click();
	    driver.findElement(By.linkText("Logout")).click();
	  }

}
