package com.csis3275;


// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;



public class CustomerManageTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

	}

	@After
	public void tearDown() {
		driver.quit();
	}

	//This test edits information from a customer and verifies if the new information was updated
	@Test
	public void customerManage() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(1900, 1020));
		driver.findElement(By.id("usernameForm")).click();
		driver.findElement(By.id("usernameForm")).sendKeys("admin");
		driver.findElement(By.id("passwordForm")).sendKeys("admin");
		driver.findElement(By.id("passwordForm")).sendKeys(Keys.ENTER);
		driver.findElement(By.linkText("Edit")).click();
		driver.findElement(By.id("fName")).click();
		driver.findElement(By.id("fName")).clear();
		driver.findElement(By.id("fName")).sendKeys("Johnson");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".dataRows:nth-child(2)")).click();
		
		//Asserts that new customer name is included
		assertThat(driver.findElement(By.xpath("/html/body/div[2]/table/tbody/tr[2]/td[2]")).getText(), is("Johnson"));
		
	}
}
