package com.csis3275;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

public class InvoiceGenerationTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	// Tests if the invoice file was generated
	@Test
	public void pdfTest() {
		driver.get("http://localhost:8080/");
		driver.findElement(By.id("usernameForm")).click();
		driver.findElement(By.id("usernameForm")).sendKeys("admin");
		driver.findElement(By.cssSelector(".form-group:nth-child(3) > .col-md-9")).click();
		driver.findElement(By.id("passwordForm")).click();
		driver.findElement(By.id("passwordForm")).sendKeys("admin");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".roomNav3 > a")).click();
		driver.findElement(By.linkText("Edit")).click();
		String id = driver.findElement(By.id("bid")).getAttribute("value");
		driver.findElement(By.name("tax")).click();
		{
			WebElement dropdown = driver.findElement(By.name("tax"));
			dropdown.findElement(By.xpath("//option[. = 'AB']")).click();
		}
		driver.findElement(By.name("tax")).click();
		driver.findElement(By.cssSelector(".btn-info")).click();
		driver.findElement(By.xpath("//div[2]/div[2]")).click();
		File file = new File("invoices\\invoice_booking_" + id + ".pdf");
		assertTrue(file.exists());
	}

}
