package com.csis3275;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ManageBookingsTests {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void createBookingTest() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(1161, 762));
		driver.findElement(By.id("usernameForm")).click();
		driver.findElement(By.id("usernameForm")).sendKeys("admin");
		driver.findElement(By.id("passwordForm")).click();
		driver.findElement(By.id("passwordForm")).sendKeys("admin");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".roomNav3 > a")).click();
		driver.findElement(By.name("room")).click();
		{
			WebElement dropdown = driver.findElement(By.name("room"));
			dropdown.findElement(By.id("301")).click();
		}
		driver.findElement(By.name("room")).click();
		driver.findElement(By.id("bookingDateStart")).click();
		driver.findElement(By.id("bookingDateStart")).sendKeys("12-31-2020");
		driver.findElement(By.id("bookindDateEnd")).click();
		driver.findElement(By.id("bookindDateEnd")).sendKeys("01-03-2021");
		{
			WebElement element = driver.findElement(By.id("booking"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		driver.findElement(By.id("booking")).click();
		driver.findElement(By.cssSelector(".btn")).click();
		assertEquals("Booking was successfully created!", driver.findElement(By.id("successMessage")).getText());
	}

	@Test
	public void deletebooking() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(1162, 763));
		driver.findElement(By.id("usernameForm")).click();
		driver.findElement(By.id("usernameForm")).sendKeys("admin");
		driver.findElement(By.cssSelector(".form-group:nth-child(3)")).click();
		driver.findElement(By.id("passwordForm")).click();
		driver.findElement(By.id("passwordForm")).sendKeys("admin");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".roomNav3 > a")).click();
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.cssSelector(".dataRows:nth-child(2) > td:nth-child(16) > a")).click();
		driver.findElement(By.cssSelector(".alert")).click();
	}

	@Test
	public void editBookingTest() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(1161, 762));
		driver.findElement(By.id("usernameForm")).click();
		driver.findElement(By.id("usernameForm")).sendKeys("admin");
		driver.findElement(By.id("user")).click();
		driver.findElement(By.id("passwordForm")).click();
		driver.findElement(By.id("passwordForm")).sendKeys("admin");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".roomNav3 > a")).click();
		driver.findElement(By.cssSelector(".dataRows:nth-child(3) > td:nth-child(15) > a")).click();
		driver.findElement(By.cssSelector("label:nth-child(2) > input")).click();
		driver.findElement(By.cssSelector(".btn-primary")).click();
		assertEquals("true", driver.findElement(By.cssSelector(".dataRows:nth-child(3) > td:nth-child(7)")).getText());
	}
}
