package com.csis3275;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchRoomsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  //This test makes a search for a range of dates and verify that the correct amount of rooms was found
  @Test
  public void searchRooms() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1900, 1020));
    driver.findElement(By.id("usernameForm")).click();
    driver.findElement(By.id("usernameForm")).sendKeys("doeJohn");
    driver.findElement(By.id("passwordForm")).click();
    driver.findElement(By.id("passwordForm")).sendKeys("passJohnDoe");
    driver.findElement(By.id("passwordForm")).sendKeys(Keys.ENTER);
    
    ((JavascriptExecutor) driver).executeScript("document.getElementById('startDateFormControl').removeAttribute('readonly');");
    ((JavascriptExecutor) driver).executeScript("document.getElementById('endDateFormControl').removeAttribute('readonly');");
    
    driver.findElement(By.id("startDateFormControl")).sendKeys("22-12-2020");
    driver.findElement(By.id("endDateFormControl")).sendKeys("23-12-2020");
    
//    
    driver.findElement(By.id("submitSearch")).click();
    driver.findElement(By.cssSelector(".dataRows:nth-child(2) > .availRooms")).click();
    
    //Asserts that 2 premium rooms were found
	assertThat(driver.findElement(By.xpath("/html/body/div[2]/div/table/tbody/tr[2]/td[8]")).getText(), is("2"));

  }
}
