package com.csis3275;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class StaffFacilitiesBlackBoxTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginStaffFacilities() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.id("usernameForm")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(3)")).click();
    driver.findElement(By.id("usernameForm")).sendKeys("admin");
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(4)")).click();
    driver.findElement(By.id("passwordForm")).sendKeys("admin");
    driver.findElement(By.cssSelector(".form-group:nth-child(5) > .col-md-offset-3")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("username")).sendKeys("doeJohn");
    driver.findElement(By.id("password")).sendKeys("passJohnDoe");
    driver.findElement(By.cssSelector(".roomNav4 > a")).click();
    driver.findElement(By.id("facilityName")).click();
    driver.findElement(By.id("facilityName")).sendKeys("TESTINGROOM");
    driver.findElement(By.id("facilityType")).click();
    {
      WebElement dropdown = driver.findElement(By.id("facilityType"));
      dropdown.findElement(By.xpath("//option[. = 'Meeting Room']")).click();
    }
    driver.findElement(By.id("facilityType")).click();
    driver.findElement(By.id("capacity")).sendKeys("1");
    driver.findElement(By.id("capacity")).click();
    driver.findElement(By.id("capacity")).sendKeys("2");
    driver.findElement(By.id("capacity")).click();
    {
      WebElement element = driver.findElement(By.id("capacity"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("capacity")).sendKeys("3");
    driver.findElement(By.id("capacity")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("body")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(3) > .col-md-3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(3) > .col-md-3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(3) > .col-md-3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".form-group:nth-child(3)")).click();
    driver.findElement(By.id("capacity")).sendKeys("5");
    driver.findElement(By.cssSelector(".col-md-offset-3")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".dataRows:nth-child(7) > td:nth-child(6) > a")).click();
  }
}
