package com.csis3275;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ViewEditProfileTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void viewProfile() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(1154, 758));
		driver.findElement(By.id("usernameForm")).click();
		driver.findElement(By.id("usernameForm")).sendKeys("doeJohn");
		driver.findElement(By.id("passwordForm")).click();
		driver.findElement(By.id("passwordForm")).sendKeys("11111111");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.linkText("My Profile")).click();
		assertEquals("doeJohn", driver.findElement(By.xpath("//h2")).getText());
	}

	@Test
	public void editProfile() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(1157, 760));
		driver.findElement(By.id("usernameForm")).click();
		driver.findElement(By.id("usernameForm")).sendKeys("doeJohn");
		driver.findElement(By.id("passwordForm")).click();
		driver.findElement(By.id("passwordForm")).sendKeys("11111111");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.linkText("My Profile")).click();
		driver.findElement(By.id("editBtn")).click();
		driver.findElement(By.cssSelector(".modal-content")).findElement(By.name("fName")).sendKeys("Fuuuu");
//		driver.findElement(By.name("fName"));
//		driver.findElement(By.name("fName")).sendKeys("Johnny");
//		driver.findElement(By.id("saveEdit")).click();
//		driver.findElement(By.id("editBtn")).click();
//		driver.findElement(By.name("fName")).click();
	}
}
